version: '3.9'

services:
  db:
    container_name: tipen-demo-pern-db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-tipen-demo-pern-db}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - 5434:5432
    expose:
      - 5434
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db:
    driver: local


